config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # post 'likes/create'
  get 'comments/new'
  get 'comments/create'

  get 'users/index'
  get 'users/show'
  devise_for :users
  root to: "home#index"

  resources :posts do
    collection do
      post :addcomment
      post :like
    end
  end

  resources :friendships do
    collection do
      get :add_friend
      get :view
      post :accept_decline
      get  :friendlist
      delete :unfriend
      
    
    end
  end
  resources :messages do
    collection do
      post :addmessage

    end    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/Friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sent_by, class_name: 'User', foreign_key: 'sent_by_id'
  belongs_to :sent_to, class_name: 'User', foreign_key: 'sent_to_id'
  scope :friends, -> { where('status =?', 1 )}
  scope :not_friends, -> { where('status =?', 2) }
  scope :pending, -> { where('status =?', 0) }
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, dependent: :destroy
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sent_by, class_name: 'User', foreign_key: 'sent_by_id'
  belongs_to :sent_to, class_name: 'User', foreign_key: 'sent_to_id'
  scope :friends, -> { where('status =?', true) }
  scope :not_friends, -> { where('status =?', false) }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :reciever, class_name: 'User', foreign_key: 'reciever_id'
end

app/models/pagereference.rb
class Pagereference < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image,:dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
  #has_many :authentications
  #has_many :friendships, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :messages
         
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    #@comments=Post.all.order(updated_at: :desc)
  end

  def create
    
  end
  def index
    # @p=Friendship.where(user_id: current_user.id,status: 1)
    # @posts=Post.all.order(updated_at: :desc)
    # post_ids=@posts.pluck(:id)
    # @comments=Comment.where(post_id: post_ids)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def create
   
    
  end
  def show
   

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    #@p=Friendship.where(user_id: current_user.id,status: 1)
    
    add_user_ids=Friendship.where(:sent_by_id=>current_user.id,:status=>1).pluck(:sent_to_id)
    requested_user_ids=Friendship.where(:sent_to_id=>current_user.id,:status=>1).pluck(:sent_by_id)
  


    
    all_user_ids=(requested_user_ids + add_user_ids + [current_user.id]).uniq
    @f=User.where(:id=>all_user_ids)
   

    @posts=Post.where(user_id: @f.ids)
    post_ids=@posts.pluck(:id)
    
    
    
  end

  def show
    @post=Post.find_by(id: params[:id])
    @comments=Comment.where(post_id: @post.id).order(updated_at: :desc) if @post
    

  end

  def new
    @post=Post.new
  end

  def create
   
    @psts = Post.new(title: params[:post][:Title], content: params[:post][:Content],image: params[:post][:image],user_id: current_user.id) 
    if @psts.save
      redirect_to posts_path


   end
  end
  def addcomment
  
    @comment=Comment.new(reaction: params[:post][:reaction],user_id: current_user.id,post_id: params[:post][:Post_id])
    @comment.save
    flash[:notice]="comment updated successfully"
    redirect_back(fallback_location: posts_path)
  end
 
  def like
    #@likes=Like.new(user_id: current_user.id,post_id: params[:id])
    @likes=Like.find_by(user_id: current_user.id,post_id: params[:id])
    if @likes.present?
      if @likes.is_like == false
        @likes.update(is_like: true)
      else
        @likes.update(is_like: false)
      end

    else
      Like.create(user_id: current_user.id,post_id: params[:id])
    end

  end 
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def likes(id=nil)
       if id.present?
           likes=Like.where(post_id: id,is_like: true).count
        end


    end
    def comment(id=nil)
        if id.present?
            comnt=Comment.where(post_id: id).count
         end
 
 
     end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_navigationbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Home', root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      
      

      <% if user_signed_in? %>

        <li class="nav-item">
        <%= link_to "Other Users",add_friend_friendships_path, class:"nav-link" %>
        </li> 
        <li class="nav-item">
        <%= link_to "Request",view_friendships_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Friendlist", friendlist_friendships_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Postlist", posts_path, class:"nav-link" %>
        </li>
        
        <li class="nav-item">
        <%= link_to "PostPage", new_post_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Chats", messages_path, class:"nav-link" %>
        </li>
        
        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

     <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>

      
      
    </ul>
    
  </div>
</nav>

app/views/home/index.html.erb
<h1>this is home</h1>