config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # post 'likes/create'
  get 'comments/new'
  get 'comments/create'

  get 'users/index'
  get 'users/show'
  devise_for :users
  root to: "home#index"

  resources :posts do
    collection do
      post :addcomment
      post :like
    end
  end

  resources :friendships do
    collection do
      get :add_friend
      get :view
      post :accept_decline
      get  :friendlist
      delete :unfriend
      
    
    end
  end
  resources :messages do
    collection do
      post :addmessage

    end    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/Friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sent_by, class_name: 'User', foreign_key: 'sent_by_id'
  belongs_to :sent_to, class_name: 'User', foreign_key: 'sent_to_id'
  scope :friends, -> { where('status =?', 1 )}
  scope :not_friends, -> { where('status =?', 2) }
  scope :pending, -> { where('status =?', 0) }
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, dependent: :destroy
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sent_by, class_name: 'User', foreign_key: 'sent_by_id'
  belongs_to :sent_to, class_name: 'User', foreign_key: 'sent_to_id'
  scope :friends, -> { where('status =?', true) }
  scope :not_friends, -> { where('status =?', false) }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :reciever, class_name: 'User', foreign_key: 'reciever_id'
end

app/models/pagereference.rb
class Pagereference < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image,:dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
  #has_many :authentications
  #has_many :friendships, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :messages
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    #@comments=Post.all.order(updated_at: :desc)
  end

  def create
    
  end
  def index
    # @p=Friendship.where(user_id: current_user.id,status: 1)
    # @posts=Post.all.order(updated_at: :desc)
    # post_ids=@posts.pluck(:id)
    # @comments=Comment.where(post_id: post_ids)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def create
   
    
  end
  def show
   

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    def index
    
       #@recievers=Message.joins(:reciever).select('users.*').where(:sender_id=>current_user.id)
       add_user_ids=Friendship.where(:sent_by_id=>current_user.id,:status=>1).pluck(:sent_to_id)
       requested_user_ids=Friendship.where(:sent_to_id=>current_user.id,:status=>1).pluck(:sent_by_id)
    
       all_user_ids=(requested_user_ids + add_user_ids).uniq
       @recievers=User.where(:id=>all_user_ids)

 
    end
    
    
  def show
    
    @reciever = User.where(id: params[:id].to_i).first
    @messages = Message.joins("LEFT OUTER JOIN users on messages.sender_id = users.id").select("users.name, messages.*").where(:sender_id => [params[:id], current_user.id]).order("messages.created_at")

  end
  def addmessage
    @msg=Message.new(sms: params[:user][:sms],reciever_id: params[:user][:user_id].to_i,sender_id: current_user.id)
    @msg.save
    #flash[:notice]="comment updated successfully"
    redirect_back(fallback_location: posts_path)
  end
  
    
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    #@p=Friendship.where(user_id: current_user.id,status: 1)
    
    add_user_ids=Friendship.where(:sent_by_id=>current_user.id,:status=>1).pluck(:sent_to_id)
    requested_user_ids=Friendship.where(:sent_to_id=>current_user.id,:status=>1).pluck(:sent_by_id)
  


    
    all_user_ids=(requested_user_ids + add_user_ids + [current_user.id]).uniq
    @f=User.where(:id=>all_user_ids)
   

    @posts=Post.where(user_id: @f.ids)
    post_ids=@posts.pluck(:id)
    
    
    
  end

  def show
    @post=Post.find_by(id: params[:id])
    @comments=Comment.where(post_id: @post.id).order(updated_at: :desc) if @post
    

  end

  def new
    @post=Post.new
  end

  def create
   
    @psts = Post.new(title: params[:post][:Title], content: params[:post][:Content],image: params[:post][:image],user_id: current_user.id) 
    if @psts.save
      redirect_to posts_path


   end
  end
  def addcomment
  
    @comment=Comment.new(reaction: params[:post][:reaction],user_id: current_user.id,post_id: params[:post][:Post_id])
    @comment.save
    flash[:notice]="comment updated successfully"
    redirect_back(fallback_location: posts_path)
  end
 
  def like
    #@likes=Like.new(user_id: current_user.id,post_id: params[:id])
    @likes=Like.find_by(user_id: current_user.id,post_id: params[:id])
    if @likes.present?
      if @likes.is_like == false
        @likes.update(is_like: true)
      else
        @likes.update(is_like: false)
      end

    else
      Like.create(user_id: current_user.id,post_id: params[:id])
    end

  end 
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def likes(id=nil)
       if id.present?
           likes=Like.where(post_id: id,is_like: true).count
        end


    end
    def comment(id=nil)
        if id.present?
            comnt=Comment.where(post_id: id).count
         end
 
 
     end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
hfgdfdrt

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
    <div class="ibox-content m-b-sm border-bottom">
      <div class="row">
        <div class="col-sm-3">
          <div class="form-group">
            <p>
              <label for="customer">Title <span class="required">*</span></label>
              <%= form.text_field :Title, :class => "form-control", required: true %>
            </p>
          </div>
        </div>
        <br>
        <br>
        <div class="col-sm-3 ">
          <div class="form-group">
            <p>
              <label for="customer">Content</label><br>
              <%= form.text_field :Content,:class => "form-control", required: true  %>
            </p>
          </div>
        </div>
        <br>
        <br>
        <div class="col-sm-3 ">
          <div class="form-group">
            <p>
              <label for="customer">Content</label><br>
              <%= form.file_field :image, accept: 'image/png, image/gif, image/jpeg' %></p>
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12 text-center">
          
            <%= form.submit%>
        </div>
      </div>  
    </div>
  <% end %>

app/views/posts/index.html.erb
<div class="container">
<ul class="list-group">
<% @posts.each do |p| %>

  
    <li class="list-group-item" > <%= p.title %>
    <li class="list-group-item" > <%= p.content %>
    <li class="list-group-item" > <%= image_tag(p.image, :size => "80x80", :alt => "Picture") %>

</li>
<div class="container">
<%=likes(p.id)%>
<%= link_to "Likes",like_posts_path(id: p.id),method: :post %>
<%=comment(p.id)%>
<%= link_to "comments" ,post_path(id: p.id),method: :get %>


    
    
</div>
<%end%>  
</ul>
</div>
<br>


      

app/views/posts/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
<ul class="list-group">


  
    <li class="list-group-item" > <%= @post.title %>
    <li class="list-group-item" > <%= @post.content %>
    <li class="list-group-item" > <%= image_tag(@post.image, :size => "80x80", :alt => "Picture") %>
    <%= form_with model: @post,url:addcomment_posts_path ,method: :post,local: true do |form| %>
     <div class="col-sm-3 text-right">
          <div class="form-group">
            <p>
            <br>
            <%= form.hidden_field :Post_id, value: @post.id %>
           
              <%= form.text_field :reaction,:class => "form-control", :placeholder=>"comment" ,required: true  %>
              
            </p>
          </div>
      </div>
    <%end%>

    <% @comments.each do |c|%>
        <li class="list-group-item" > <%= c.reaction %></li>
       

    <%end%>




</ul>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>